"""
VaultHound State Management Module

This module provides the core state structures for the VaultHound secret scanning agent.
It defines the ScanState TypedDict for managing scan execution state and the FindingModel
Pydantic model for representing discovered secrets/credentials.

State Management Overview:
- ScanState: A TypedDict that holds all state information during a repository scan
- FindingModel: A Pydantic model that validates and serializes secret findings

The state is designed to be:
1. Type-safe: Using TypedDict and Pydantic for runtime validation
2. Serializable: Findings can be stored in databases or exported
3. Extendable: New fields can be added without breaking existing code
"""

from typing import TypedDict, Optional, List, Dict, Any, Annotated
from datetime import datetime
from enum import Enum
from operator import add, or_
from pydantic import BaseModel, Field, ConfigDict
import uuid


class ScanStatus(str, Enum):
    """
    Enum representing the possible states of a repository scan.

    Attributes:
        PENDING: Scan has been queued but not started
        IN_PROGRESS: Scan is actively running
        COMPLETED: Scan finished successfully
        FAILED: Scan encountered an error
        CANCELLED: Scan was cancelled by user
        AWAITING_APPROVAL: Scan requires human approval to continue
    """

    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"
    AWAITING_APPROVAL = "awaiting_approval"


class SeverityLevel(str, Enum):
    """
    Enum representing the severity level of a finding.

    Attributes:
        CRITICAL: Immediate security risk requiring urgent action
        HIGH: Significant security risk
        MEDIUM: Moderate security risk
        LOW: Minor security risk or informational
        INFO: Informational finding, not a vulnerability
    """

    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    INFO = "info"


class SecretType(str, Enum):
    """
    Enum representing types of secrets that can be detected.

    Attributes:
        API_KEY: Generic API key
        AWS_ACCESS_KEY: AWS access key ID
        AWS_SECRET_KEY: AWS secret access key
        AWS_SESSION_TOKEN: AWS temporary session token
        GITHUB_TOKEN: GitHub personal access token
        GITLAB_TOKEN: GitLab personal access token
        JWT_TOKEN: JSON Web Token
        PRIVATE_KEY: SSH or other private key
        PASSWORD: Generic password
        DATABASE_URL: Database connection string
        ENCRYPTION_KEY: Encryption/decryption key
        OAUTH_SECRET: OAuth client secret
        CUSTOM: Custom/other secret type
    """

    API_KEY = "api_key"
    AWS_ACCESS_KEY = "aws_access_key"
    AWS_SECRET_KEY = "aws_secret_key"
    AWS_SESSION_TOKEN = "aws_session_token"
    GITHUB_TOKEN = "github_token"
    GITLAB_TOKEN = "gitlab_token"
    JWT_TOKEN = "jwt_token"
    PRIVATE_KEY = "private_key"
    PASSWORD = "password"
    DATABASE_URL = "database_url"
    ENCRYPTION_KEY = "encryption_key"
    OAUTH_SECRET = "oauth_secret"
    CUSTOM = "custom"


class FindingModel(BaseModel):
    """
    Pydantic model representing a discovered secret or credential.

    This model validates all finding data, ensures consistency, and provides
    serialization capabilities for storage and display.

    Attributes:
        id: Unique identifier for the finding
        secret_type: Type of secret discovered
        severity: Security severity level
        file_path: Path to file containing the secret
        line_number: Line number where secret was found
        column_start: Starting column of the secret
        column_end: Ending column of the secret
        commit_sha: Git commit where secret was introduced
        commit_date: Date of the commit
        commit_author: Author of the commit
        commit_message: Commit message
        context_before: Lines before the secret (for context)
        context_after: Lines after the secret (for context)
        entropy_score: Shannon entropy score (high = likely secret)
        is_canary: Whether this is a canary/token generated by VaultHound
        confirmed_real: Whether the secret has been confirmed as real
        false_positive: Whether this is marked as a false positive
        remediation_status: Status of remediation efforts
        notes: Additional notes about the finding
        discovered_at: Timestamp when the finding was discovered
        updated_at: Timestamp when the finding was last updated
    """

    model_config = ConfigDict(
        str_strip_whitespace=True, validate_assignment=True, use_enum_values=True
    )

    # Required fields
    id: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        description="Unique identifier for the finding",
    )
    secret_type: SecretType = Field(..., description="Type of secret discovered")
    severity: SeverityLevel = Field(..., description="Security severity level")
    file_path: str = Field(..., description="Path to file containing the secret")

    # Location information
    line_number: int = Field(
        ..., ge=1, description="Line number where secret was found"
    )
    column_start: Optional[int] = Field(
        default=None, ge=1, description="Starting column of the secret"
    )
    column_end: Optional[int] = Field(
        default=None, ge=1, description="Ending column of the secret"
    )

    # Git context
    commit_sha: Optional[str] = Field(
        default=None, description="Git commit where secret was introduced"
    )
    commit_date: Optional[datetime] = Field(
        default=None, description="Date of the commit"
    )
    commit_author: Optional[str] = Field(
        default=None, description="Author of the commit"
    )
    commit_message: Optional[str] = Field(default=None, description="Commit message")

    # Code context
    context_before: Optional[List[str]] = Field(
        default=None, description="Lines before the secret (for context)"
    )
    context_after: Optional[List[str]] = Field(
        default=None, description="Lines after the secret (for context)"
    )

    # Analysis metadata
    entropy_score: Optional[float] = Field(
        default=None,
        ge=0.0,
        le=8.0,
        description="Shannon entropy score (high = likely secret)",
    )
    is_canary: bool = Field(
        default=False,
        description="Whether this is a canary/token generated by VaultHound",
    )
    confirmed_real: bool = Field(
        default=False, description="Whether the secret has been confirmed as real"
    )
    false_positive: bool = Field(
        default=False, description="Whether this is marked as a false positive"
    )

    # Remediation tracking
    remediation_status: str = Field(
        default="open", description="Status of remediation efforts"
    )
    notes: Optional[str] = Field(
        default=None, description="Additional notes about the finding"
    )

    # Timestamps
    discovered_at: datetime = Field(
        default_factory=datetime.utcnow,
        description="Timestamp when the finding was discovered",
    )
    updated_at: datetime = Field(
        default_factory=datetime.utcnow,
        description="Timestamp when the finding was last updated",
    )

    def mark_false_positive(self, notes: str = "") -> None:
        """
        Mark this finding as a false positive.

        Args:
            notes: Optional notes explaining why this is a false positive
        """
        self.false_positive = True
        self.remediation_status = "false_positive"
        if notes:
            self.notes = notes
        self.updated_at = datetime.utcnow()

    def confirm_real(self) -> None:
        """Mark this finding as a confirmed real secret."""
        self.confirmed_real = True
        self.updated_at = datetime.utcnow()

    def mark_remediated(self, notes: str = "") -> None:
        """
        Mark this finding as remediated.

        Args:
            notes: Optional notes about the remediation
        """
        self.remediation_status = "remediated"
        if notes:
            self.notes = notes
        self.updated_at = datetime.utcnow()


class ScanState(TypedDict):
    """
    TypedDict representing the complete state of a repository scan.

    This TypedDict defines all state fields used throughout the scanning process.
    It provides type safety and documentation for the scan state structure.

    State Fields:
        repo_url: URL of the repository being scanned
        scan_depth: Depth of scanning (e.g., "shallow", "full", "commit_history")
        findings: List of FindingModel instances discovered during the scan
        commit_history: List of commit information from the repository
        file_tree: Dictionary representing the repository file structure
        scan_status: Current status of the scan (from ScanStatus enum)
        error_log: List of error messages encountered during scanning
        agent_scratchpad: Dictionary for agents to store intermediate data
        security_flags: Dictionary of security-related flags and thresholds
        canary_tokens: List of canary tokens planted in the repository
        human_approval_required: Whether the scan requires human approval to continue
        approved_by_human: Whether the scan has been approved by a human

    Usage:
        state: ScanState = {
            "repo_url": "https://github.com/example/repo",
            "scan_depth": "full",
            "findings": [],
            "commit_history": [],
            "file_tree": {},
            "scan_status": "pending",
            "error_log": [],
            "agent_scratchpad": {},
            "security_flags": {},
            "canary_tokens": [],
            "human_approval_required": False,
            "approved_by_human": False
        }
    """

    # Repository identification
    repo_url: str  # URL of the repository being scanned

    # Scan configuration
    scan_depth: str  # Depth of scanning: "shallow", "full", "commit_history", etc.

    # Results
    findings: Annotated[
        List[FindingModel], add
    ]  # List of FindingModel instances discovered during the scan

    # Git history
    commit_history: Annotated[
        List[Dict[str, Any]], add
    ]  # List of commit information from the repository

    # Repository structure
    file_tree: Dict[str, Any]  # Dictionary representing the repository file structure

    # Current state
    scan_status: ScanStatus  # Current status of the scan (from ScanStatus enum)

    # Error tracking
    error_log: Annotated[
        List[Dict[str, Any]], add
    ]  # List of error messages encountered during scanning

    # Agent workspace
    agent_scratchpad: Annotated[
        Dict[str, Any], or_
    ]  # Dictionary for agents to store intermediate data

    # Security configuration
    security_flags: Dict[
        str, Any
    ]  # Dictionary of security-related flags and thresholds

    # Canary token tracking
    canary_tokens: List[str]  # List of canary tokens planted in the repository

    # API Keys (stored in state for agent access)
    openai_api_key: Optional[str]  # OpenAI API key for GPT-4o analysis

    # Human approval workflow
    human_approval_required: (
        bool  # Whether the scan requires human approval to continue
    )
    approved_by_human: bool  # Whether the scan has been approved by a human


def create_initial_state(
    repo_url: str, scan_depth: str = "full", openai_api_key: Optional[str] = None
) -> ScanState:
    """
    Create an initial ScanState with default values.

    This factory function provides a convenient way to initialize a new scan state
    with sensible defaults, ensuring all required fields are properly set.

    Args:
        repo_url: URL of the repository to scan
        scan_depth: Depth of scanning (default: "full")

    Returns:
        ScanState: A new ScanState instance with default values

    Example:
        >>> state = create_initial_state("https://github.com/example/repo")
        >>> print(state["repo_url"])
        https://github.com/example/repo
    """
    return ScanState(
        repo_url=repo_url,
        scan_depth=scan_depth,
        findings=[],
        commit_history=[],
        file_tree={},
        scan_status=ScanStatus.PENDING,
        error_log=[],
        agent_scratchpad={},
        security_flags={
            "entropy_threshold": 4.5,
            "max_file_size_mb": 10,
            "scan_binaries": False,
            "scan_images": False,
            "follow_symlinks": False,
            "exclude_patterns": ["*.test.py", "*.mock.js", "node_modules/**"],
        },
        canary_tokens=[],
        human_approval_required=False,
        approved_by_human=False,
        openai_api_key=openai_api_key,
    )


def add_finding(state: ScanState, finding: FindingModel) -> None:
    """
    Add a finding to the scan state.

    This function adds a FindingModel to the state's findings list and updates
    the agent scratchpad with summary statistics.

    Args:
        state: The ScanState to add the finding to
        finding: The FindingModel to add

    Example:
        >>> state = create_initial_state("https://github.com/example/repo")
        >>> finding = FindingModel(
        ...     secret_type=SecretType.AWS_ACCESS_KEY,
        ...     severity=SeverityLevel.CRITICAL,
        ...     file_path="config/prod.yaml",
        ...     line_number=42
        ... )
        >>> add_finding(state, finding)
    """
    state["findings"].append(finding)

    # Update scratchpad with statistics
    if "finding_counts" not in state["agent_scratchpad"]:
        state["agent_scratchpad"]["finding_counts"] = {}

    counts = state["agent_scratchpad"]["finding_counts"]
    secret_type = finding.secret_type
    counts[secret_type] = counts.get(secret_type, 0) + 1


def log_error(
    state: ScanState, error_message: str, error_details: Optional[Dict[str, Any]] = None
) -> None:
    """
    Log an error to the scan state.

    Args:
        state: The ScanState to log the error to
        error_message: Description of the error
        error_details: Optional dictionary with additional error details

    Example:
        >>> state = create_initial_state("https://github.com/example/repo")
        >>> log_error(state, "Failed to clone repository", {"repo_url": "https://github.com/bad/repo"})
    """
    error_entry = {
        "timestamp": datetime.utcnow().isoformat(),
        "message": error_message,
        "details": error_details or {},
    }
    state["error_log"].append(error_entry)


def set_scan_status(state: ScanState, status: ScanStatus) -> None:
    """
    Update the scan status.

    This function also handles the human approval workflow by checking
    if approval is required when switching to certain statuses.

    Args:
        state: The ScanState to update
        status: The new ScanStatus

    Example:
        >>> state = create_initial_state("https://github.com/example/repo")
        >>> set_scan_status(state, ScanStatus.IN_PROGRESS)
    """
    state["scan_status"] = status

    # Check if we need human approval for high-severity findings
    if status == ScanStatus.IN_PROGRESS:
        critical_findings = [
            f
            for f in state["findings"]
            if f.severity == SeverityLevel.CRITICAL and not f.false_positive
        ]
        if len(critical_findings) > 0:
            state["human_approval_required"] = True
